version: 0.1
phases:
  build:
    commands:
      - npm install
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket node4lambda-bucket --output-template-file NewSamTemplate.yml


artifacts:
  type: zip
  files:
    - app.js
    - package.json
    - bin/*
    - routes/*
    - views/*
    - public/**/*
    - node_modules/**/*
    - NewSamTemplate.yml